import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/components/Navbar';
import { AuthProvider } from './lib/authContext';
import { StrictMode } from 'react';
import { DateProvider } from './lib/dateContext';

const comfortaa = localFont({
  src: './fonts/Comfortaa-VariableFont_wght.ttf',
  variable: '--font-comfortaa',
  weight: '100 900'
});

export const metadata = {
  title: 'Prodify',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <StrictMode>
      <html lang="en">
        <head>
          <meta charSet="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </head>

        <body className={`${comfortaa.className}  antialiased bg-background flex h-screen`}>
          {/* Hooks and Providers */}
          <AuthProvider>
            <DateProvider>
              {/* Main Layout */}
              <div className="h-screen w-screen flex">
                {/* Left Sidebar */}
                <Navbar />

                {/* Right Section */}
                <div className="flex flex-col flex-1">
                  {/* Top Navbar */}

                  {/* Main Content */}
                  <main className="flex-1 bg-dark-8  overflow-auto justify-items-center">{children}</main>
                </div>
              </div>
            </DateProvider>
          </AuthProvider>
        </body>
      </html>
    </StrictMode>
  );
}
